# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  8 2023, 10:42:25) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: reportlab\pdfbase\_fontdata_enc_symbol.pyc
# Compiled at: 2013-03-27 15:37:42
SymbolEncoding = (None, None, None, None, None, None, None, None, None, None, None,
                  None, None, None, None, None, None, None, None, None, None, None,
                  None, None, None, None, None, None, None, None, None, None, 'space',
                  'exclam', 'universal', 'numbersign', 'existential', 'percent',
                  'ampersand', 'suchthat', 'parenleft', 'parenright', 'asteriskmath',
                  'plus', 'comma', 'minus', 'period', 'slash', 'zero', 'one', 'two',
                  'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'colon',
                  'semicolon', 'less', 'equal', 'greater', 'question', 'congruent',
                  'Alpha', 'Beta', 'Chi', 'Delta', 'Epsilon', 'Phi', 'Gamma', 'Eta',
                  'Iota', 'theta1', 'Kappa', 'Lambda', 'Mu', 'Nu', 'Omicron', 'Pi',
                  'Theta', 'Rho', 'Sigma', 'Tau', 'Upsilon', 'sigma1', 'Omega', 'Xi',
                  'Psi', 'Zeta', 'bracketleft', 'therefore', 'bracketright', 'perpendicular',
                  'underscore', 'radicalex', 'alpha', 'beta', 'chi', 'delta', 'epsilon',
                  'phi', 'gamma', 'eta', 'iota', 'phi1', 'kappa', 'lambda', 'mu',
                  'nu', 'omicron', 'pi', 'theta', 'rho', 'sigma', 'tau', 'upsilon',
                  'omega1', 'omega', 'xi', 'psi', 'zeta', 'braceleft', 'bar', 'braceright',
                  'similar', None, None, None, None, None, None, None, None, None,
                  None, None, None, None, None, None, None, None, None, None, None,
                  None, None, None, None, None, None, None, None, None, None, None,
                  None, None, 'Euro', 'Upsilon1', 'minute', 'lessequal', 'fraction',
                  'infinity', 'florin', 'club', 'diamond', 'heart', 'spade', 'arrowboth',
                  'arrowleft', 'arrowup', 'arrowright', 'arrowdown', 'degree', 'plusminus',
                  'second', 'greaterequal', 'multiply', 'proportional', 'partialdiff',
                  'bullet', 'divide', 'notequal', 'equivalence', 'approxequal', 'ellipsis',
                  'arrowvertex', 'arrowhorizex', 'carriagereturn', 'aleph', 'Ifraktur',
                  'Rfraktur', 'weierstrass', 'circlemultiply', 'circleplus', 'emptyset',
                  'intersection', 'union', 'propersuperset', 'reflexsuperset', 'notsubset',
                  'propersubset', 'reflexsubset', 'element', 'notelement', 'angle',
                  'gradient', 'registerserif', 'copyrightserif', 'trademarkserif',
                  'product', 'radical', 'dotmath', 'logicalnot', 'logicaland', 'logicalor',
                  'arrowdblboth', 'arrowdblleft', 'arrowdblup', 'arrowdblright',
                  'arrowdbldown', 'lozenge', 'angleleft', 'registersans', 'copyrightsans',
                  'trademarksans', 'summation', 'parenlefttp', 'parenleftex', 'parenleftbt',
                  'bracketlefttp', 'bracketleftex', 'bracketleftbt', 'bracelefttp',
                  'braceleftmid', 'braceleftbt', 'braceex', None, 'angleright', 'integral',
                  'integraltp', 'integralex', 'integralbt', 'parenrighttp', 'parenrightex',
                  'parenrightbt', 'bracketrighttp', 'bracketrightex', 'bracketrightbt',
                  'bracerighttp', 'bracerightmid', 'bracerightbt', None)