# Embedded file name: Calculos\listados.pyc
versionCEX = 2.1
esRC = ''
programaVersion = 'CEXv%s%s' % (versionCEX, esRC)
programaVersionExe = '%s.exe' % programaVersion
versionXML = 1.0
versionDatosEnergeticosXML = 2.0

def getVersionGuardada(versionGuardada):
    if '.exe' in versionGuardada:
        versionGuardada = versionGuardada.replace('.exe', ' ')
    v = float(versionGuardada.split(' ')[0].split('_')[0].split('v')[1])
    return v


def versionArchivoCoincideConVersionPrograma(versionGuardada, programa):
    """
    M\xe9todo: versionArchivoCoincideConVersionPrograma
    Argumentos: 
        versionGuardada de archivo: si el archivo que se est\xe1 cargando es CEXv1.3 Residencial
        programa: version del programa: Residencial, Peque\xf1oTerciario, GranTerciario
    Se utiliza al cargar un conjuntoMM desde archivo.
    Devuelve True si el programa se grab\xf3 con la misma versi\xf3n y tipo (res, pt, gt) que la herramienta actual. False en caso contrario
    """
    if '.exe' in versionGuardada:
        versionGuardada = versionGuardada.replace('.exe', ' ')
    if versionGuardada != '%s %s' % (programaVersion, programa):
        return False
    else:
        return True


class Localizacion:

    def __init__(self):
        self.provincias = [(u'A Coru\xf1a', _(u'A Coru\xf1a')),
         (u'\xc1lava', _(u'\xc1lava')),
         (u'Albacete', _(u'Albacete')),
         (u'Alicante', _(u'Alicante')),
         (u'Almer\xeda', _(u'Almer\xeda')),
         (u'Asturias', _(u'Asturias')),
         (u'\xc1vila', _(u'\xc1vila')),
         (u'Badajoz', _(u'Badajoz')),
         (u'Barcelona', _(u'Barcelona')),
         (u'Burgos', _(u'Burgos')),
         (u'C\xe1ceres', _(u'C\xe1ceres')),
         (u'C\xe1diz', _(u'C\xe1diz')),
         (u'Cantabria', _(u'Cantabria')),
         (u'Castell\xf3n', _(u'Castell\xf3n')),
         (u'Ceuta', _(u'Ceuta')),
         (u'Ciudad Real', _(u'Ciudad Real')),
         (u'C\xf3rdoba', _(u'C\xf3rdoba')),
         (u'Cuenca', _(u'Cuenca')),
         (u'Girona', _(u'Girona')),
         (u'Granada', _(u'Granada')),
         (u'Guadalajara', _(u'Guadalajara')),
         (u'Guip\xfazcoa', _(u'Guip\xfazcoa')),
         (u'Huelva', _(u'Huelva')),
         (u'Huesca', _(u'Huesca')),
         (u'Illes Balears', _(u'Illes Balears')),
         (u'Ja\xe9n', _(u'Ja\xe9n')),
         (u'La Rioja', _(u'La Rioja')),
         (u'Las Palmas', _(u'Las Palmas')),
         (u'Le\xf3n', _(u'Le\xf3n')),
         (u'Lugo', _(u'Lugo')),
         (u'Lleida', _(u'Lleida')),
         (u'Madrid', _(u'Madrid')),
         (u'M\xe1laga', _(u'M\xe1laga')),
         (u'Melilla', _(u'Melilla')),
         (u'Murcia', _(u'Murcia')),
         (u'Navarra', _(u'Navarra')),
         (u'Ourense', _(u'Ourense')),
         (u'Palencia', _(u'Palencia')),
         (u'Pontevedra', _(u'Pontevedra')),
         (u'Salamanca', _(u'Salamanca')),
         (u'Santa Cruz de Tenerife', _(u'Santa Cruz de Tenerife')),
         (u'Segovia', _(u'Segovia')),
         (u'Sevilla', _(u'Sevilla')),
         (u'Soria', _(u'Soria')),
         (u'Tarragona', _(u'Tarragona')),
         (u'Teruel', _(u'Teruel')),
         (u'Toledo', _(u'Toledo')),
         (u'Valencia', _(u'Valencia')),
         (u'Valladolid', _(u'Valladolid')),
         (u'Vizcaya', _(u'Vizcaya')),
         (u'Zamora', _(u'Zamora')),
         (u'Zaragoza', _(u'Zaragoza'))]
        self.diccionarioProvincias = {u'A Coru\xf1a': 0,
         u'\xc1lava': 1,
         u'Albacete': 2,
         u'Alicante': 3,
         u'Almer\xeda': 4,
         u'Asturias': 5,
         u'\xc1vila': 6,
         u'Badajoz': 7,
         u'Barcelona': 8,
         u'Burgos': 9,
         u'C\xe1ceres': 10,
         u'C\xe1diz': 11,
         u'Cantabria': 12,
         u'Castell\xf3n': 13,
         u'Ceuta': 14,
         u'Ciudad Real': 15,
         u'C\xf3rdoba': 16,
         u'Cuenca': 17,
         u'Girona': 18,
         u'Granada': 19,
         u'Guadalajara': 20,
         u'Guip\xfazcoa': 21,
         u'Huelva': 22,
         u'Huesca': 23,
         u'Illes Balears': 24,
         u'Ja\xe9n': 25,
         u'La Rioja': 26,
         u'Las Palmas': 27,
         u'Le\xf3n': 28,
         u'Lugo': 29,
         u'Lleida': 30,
         u'Madrid': 31,
         u'M\xe1laga': 32,
         u'Melilla': 33,
         u'Murcia': 34,
         u'Navarra': 35,
         u'Ourense': 36,
         u'Palencia': 37,
         u'Pontevedra': 38,
         u'Salamanca': 39,
         u'Santa Cruz de Tenerife': 40,
         u'Segovia': 41,
         u'Sevilla': 42,
         u'Soria': 43,
         u'Tarragona': 44,
         u'Teruel': 45,
         u'Toledo': 46,
         u'Valencia': 47,
         u'Valladolid': 48,
         u'Vizcaya': 49,
         u'Zamora': 50,
         u'Zaragoza': 51}
        self.diccionarioCapitalesDeProvincia = {u'A Coru\xf1a': u'A Coru\xf1a',
         u'\xc1lava': u'Vitoria',
         u'Albacete': u'Albacete',
         u'Alicante': u'Alicante',
         u'Almer\xeda': u'Almer\xeda',
         u'Asturias': u'Oviedo',
         u'\xc1vila': u'Avila',
         u'Badajoz': u'Badajoz',
         u'Barcelona': u'Barcelona',
         u'Burgos': u'Burgos',
         u'C\xe1ceres': u'C\xe1ceres',
         u'C\xe1diz': u'C\xe1diz',
         u'Cantabria': u'Santander',
         u'Castell\xf3n': u'Castell\xf3n de la Plana',
         u'Ceuta': u'Ceuta',
         u'Ciudad Real': u'Ciudad Real',
         u'C\xf3rdoba': u'C\xf3rdoba',
         u'Cuenca': u'Cuenca',
         u'Girona': u'Girona',
         u'Granada': u'Granada',
         u'Guadalajara': u'Guadalajara',
         u'Guip\xfazcoa': u'San Sebasti\xe1n',
         u'Huelva': u'Huelva',
         u'Huesca': u'Huesca',
         u'Illes Balears': u'Palma de Mallorca',
         u'Ja\xe9n': u'Ja\xe9n',
         u'La Rioja': u'Logro\xf1o',
         u'Las Palmas': u'Las Palmas de Gran Canaria',
         u'Le\xf3n': u'Le\xf3n',
         u'Lugo': u'Lugo',
         u'Lleida': u'L\xe9rida',
         u'Madrid': u'Madrid ',
         u'M\xe1laga': u'M\xe1laga',
         u'Melilla': u'Melilla',
         u'Murcia': u'Murcia',
         u'Navarra': u'Pamplona',
         u'Ourense': u'Ourense ',
         u'Palencia': u'Palencia',
         u'Pontevedra': u'Pontevedra',
         u'Salamanca': u'Salamanca',
         u'Santa Cruz de Tenerife': u'Santa Cruz de Tenerife',
         u'Segovia': u'Segovia',
         u'Sevilla': u'Sevilla',
         u'Soria': u'Soria',
         u'Tarragona': u'Tarragona',
         u'Teruel': u'Teruel',
         u'Toledo': u'Toledo',
         u'Valencia': u'Valencia',
         u'Valladolid': u'Valladolid',
         u'Vizcaya': u'Bilbao',
         u'Zamora': u'Zamora',
         u'Zaragoza': u'Zaragoza'}
        self.ciudadRepresentativa = {'alpha1': [u'',
                    'alpha1',
                    'V',
                    'IV'],
         'alpha2': [u'',
                    'alpha2',
                    'V',
                    'IV'],
         'alpha3': [u'',
                    'alpha3',
                    'V',
                    'V'],
         'alpha4': [u'',
                    'alpha4',
                    'V',
                    'V'],
         'A1': [u'',
                'A1',
                'V',
                'II'],
         'A2': [u'',
                'A2',
                'V',
                'V'],
         'A3': [u'C\xe1diz',
                'A3',
                'W',
                'V'],
         'A4': [u'Almer\xeda',
                'A4',
                'W',
                'V'],
         'B1': [u'',
                'B1',
                'V',
                'II'],
         'B2': [u'',
                'B2',
                'V',
                'V'],
         'B3': [u'Valencia',
                'B3',
                'W',
                'IV'],
         'B4': [u'Sevilla',
                'B4',
                'W',
                'V'],
         'C1': [u'Bilbao',
                'C1',
                'W',
                'I'],
         'C2': [u'Barcelona',
                'C2',
                'W',
                'III'],
         'C3': [u'Granada',
                'C3',
                'Y',
                'V'],
         'C4': [u'Toledo',
                'C4',
                'X',
                'V'],
         'D1': [u'',
                'D1',
                'Y',
                'II'],
         'D2': [u'Zamora',
                'D2',
                'Y',
                'IV'],
         'D3': [u'Madrid',
                'D3',
                'Y',
                'IV'],
         'E1': [u'',
                'E1',
                'Z',
                'III']}
        self.listadoCCAA = [[_(u'Andaluc\xeda'), [u'Almer\xeda',
           u'C\xe1diz',
           u'C\xf3rdoba',
           u'Granada',
           u'Huelva',
           u'Ja\xe9n',
           u'M\xe1laga',
           u'Sevilla']],
         [_(u'Arag\xf3n'), [u'Huesca', u'Teruel', u'Zaragoza']],
         [_(u'Principado de Asturias'), [u'Asturias']],
         [_(u'Islas Baleares'), [u'Illes Balears']],
         [_(u'Canarias'), [u'Las Palmas', u'Santa Cruz de Tenerife']],
         [_(u'Cantabria'), [u'Cantabria']],
         [_(u'Castilla - La Mancha'), [u'Albacete',
           u'Ciudad Real',
           u'Cuenca',
           u'Guadalajara',
           u'Toledo']],
         [_(u'Castilla y Le\xf3n'), [u'Burgos',
           u'\xc1vila',
           u'Le\xf3n',
           u'Palencia',
           u'Salamanca',
           u'Segovia',
           u'Soria',
           u'Valladolid',
           u'Zamora']],
         [_(u'Catalu\xf1a'), [u'Barcelona',
           u'Girona',
           u'Lleida',
           u'Tarragona']],
         [_(u'Comunidad Valenciana'), [u'Castell\xf3n', u'Alicante', u'Valencia']],
         [_(u'Extremadura'), [u'C\xe1ceres', u'Badajoz']],
         [_(u'Galicia'), [u'A Coru\xf1a',
           u'Lugo',
           u'Ourense',
           u'Pontevedra']],
         [_(u'La Rioja'), [u'La Rioja']],
         [_(u'Comunidad de Madrid'), [u'Madrid']],
         [_(u'Comunidad Foral de Navarra'), [u'Navarra']],
         [_(u'Pa\xeds Vasco'), [u'\xc1lava', u'Guip\xfazcoa', u'Vizcaya']],
         [_(u'Murcia'), [u'Murcia']],
         [_(u'Ciudad Aut\xf3noma de Ceuta'), [u'Ceuta']],
         [_(u'Ciudad Aut\xf3noma de Melilla'), [u'Melilla']]]
        self.listadoGeneral = [[u'A Coru\xf1a', [[u'Arteixo',
            'C1',
            'W',
            'II'],
           [u'Carballo',
            'C1',
            'W',
            'II'],
           [u'A Coru\xf1a',
            'C1',
            'W',
            'II'],
           [u'Ferrol',
            'C1',
            'W',
            'II'],
           [u'Nar\xf3n',
            'C1',
            'W',
            'II'],
           [u'Oleiros',
            'C1',
            'W',
            'II'],
           [u'Ribeira',
            'C1',
            'W',
            'II'],
           [u'Santiago de Compostela',
            'D1',
            'W',
            'II']]],
         [u'\xc1lava', [[u'Amurrio',
            'D1',
            'Y',
            'II'],
           [u'Llodio',
            'D1',
            'Y',
            'II'],
           [u'Salvatierra',
            'E1',
            'Y',
            'II'],
           [u'Vitoria-Gasteiz',
            'D1',
            'Y',
            'II']]],
         [u'Albacete', [[u'Albacete ',
            'D3',
            'Z',
            'IV'],
           [u'Almansa',
            'D3',
            'Z',
            'IV'],
           [u'Hellin',
            'D3',
            'Z',
            'IV'],
           [u'Villarrobledo',
            'D3',
            'Z',
            'IV']]],
         [u'Alicante', [[u'Alcoy',
            'C3',
            'Y',
            'V'],
           [u'Alicante ',
            'B4',
            'W',
            'V'],
           [u'Benidorm',
            'B4',
            'W',
            'V'],
           [u'Crevillent',
            'B4',
            'W',
            'V'],
           [u'D\xe9nia',
            'B4',
            'W',
            'V'],
           [u'Elche',
            'B4',
            'W',
            'V'],
           [u'Elda',
            'C3',
            'X',
            'V'],
           [u'Ibi',
            'D3',
            'Z',
            'V'],
           [u'J\xe1vea',
            'B4',
            'W',
            'V'],
           [u'Novelda',
            'B4',
            'X',
            'V'],
           [u'Orihuela',
            'B4',
            'W',
            'V'],
           [u'Petrer',
            'C3',
            'Y',
            'V'],
           [u'San Vicente del Raspeig',
            'B4',
            'W',
            'V'],
           [u'Torrevieja',
            'B4',
            'W',
            'V'],
           [u'Villajoyosa',
            'B4',
            'W',
            'V'],
           [u'Villena',
            'C3',
            'Y',
            'V']]],
         [u'Almer\xeda', [[u'Adra',
            'A4',
            'W',
            'V'],
           [u'Almer\xeda ',
            'A4',
            'W',
            'V'],
           [u'El Ejido',
            'A4',
            'W',
            'V'],
           [u'Roquetas de mar',
            'A4',
            'W',
            'V']]],
         [u'Asturias', [[u'Avil\xe9s',
            'C1',
            'X',
            'I'],
           [u'Castrill\xf3n',
            'C1',
            'X',
            'I'],
           [u'Gij\xf3n',
            'C1',
            'X',
            'I'],
           [u'Langreo',
            'D1',
            'X',
            'I'],
           [u'Mieres',
            'D1',
            'X',
            'I'],
           [u'Oviedo',
            'D1',
            'X',
            'I'],
           [u'San Mart\xedn del Rey Aurelio',
            'D1',
            'X',
            'I'],
           [u'Siero',
            'D1',
            'X',
            'I']]],
         [u'\xc1vila', [[u'Arenas de San Pedro',
            'D2',
            'Z',
            'IV'],
           [u'Ar\xe9valo',
            'D1',
            'Z',
            'IV'],
           [u'\xc1vila ',
            'E1',
            'Z',
            'IV'],
           [u'El Barraco',
            'E1',
            'Z',
            'IV'],
           [u'Las Navas del Marqu\xe9s',
            'E1',
            'Z',
            'IV']]],
         [u'Badajoz', [[u'Almendralejo',
            'C4',
            'X',
            'V'],
           [u'Badajoz ',
            'C4',
            'X',
            'V'],
           [u'Don Benito',
            'C4',
            'X',
            'V'],
           [u'M\xe9rida',
            'C4',
            'X',
            'V'],
           [u'Villanueva de la Serena',
            'C4',
            'X',
            'V']]],
         [u'Barcelona', [[u'Badalona',
            'C2',
            'W',
            'III'],
           [u'Barber\xe1 del Vall\xe9s',
            'C2',
            'W',
            'III'],
           [u'Barcelona ',
            'C2',
            'W',
            'III'],
           [u'Castelldefels',
            'C2',
            'W',
            'III'],
           [u'Cerdanyola del Valles',
            'C2',
            'W',
            'III'],
           [u'Cornell\xe1 de Llobregat',
            'C2',
            'W',
            'III'],
           [u'Gav\xe1',
            'C2',
            'W',
            'III'],
           [u'Granollers',
            'C2',
            'W',
            'III'],
           [u'L\xb4Hospitalet de Llobregat',
            'C2',
            'W',
            'III'],
           [u'Igualada',
            'D2',
            'X',
            'III'],
           [u'Manresa',
            'C2',
            'X',
            'III'],
           [u'El Masnou',
            'C2',
            'W',
            'III'],
           [u'Matar\xf3',
            'C2',
            'W',
            'III'],
           [u'Mollet del Vall\xe9s',
            'C2',
            'W',
            'III'],
           [u'Moncada i Reixach',
            'C2',
            'W',
            'III'],
           [u'El Prat de Llobregat',
            'C2',
            'W',
            'III'],
           [u'Premia de Mar',
            'C2',
            'W',
            'III'],
           [u'Ripollet',
            'C2',
            'W',
            'III'],
           [u'Rub\xed',
            'C2',
            'W',
            'III'],
           [u'Sabadell',
            'C2',
            'W',
            'III'],
           [u'Sant Adri\xe1 de Bes\xf3s',
            'C2',
            'W',
            'III'],
           [u'Sant Boi de Llobregat',
            'C2',
            'W',
            'III'],
           [u'Sant Cugat del Vall\xe9s',
            'C2',
            'W',
            'III'],
           [u'Sant Feli\xfa de Llobregat',
            'C2',
            'W',
            'III'],
           [u'Mollet del Vall\xe9s',
            'C2',
            'W',
            'III'],
           [u'Sant Joan Desp\xed',
            'C2',
            'W',
            'III'],
           [u'Sant Pere de Ribes',
            'C2',
            'W',
            'III'],
           [u'Sant Vicen\xe7 dels Horts',
            'C2',
            'W',
            'III'],
           [u'Santa Coloma de Gramanet',
            'C2',
            'W',
            'III'],
           [u'Terrasa',
            'D2',
            'X',
            'III'],
           [u'Vic',
            'D1',
            'Y',
            'III'],
           [u'Viladecans',
            'C2',
            'W',
            'III'],
           [u'Vilafranca del Pened\xe9s',
            'C2',
            'X',
            'III'],
           [u'Vilanova i la Geltr\xfa',
            'C2',
            'W',
            'III']]],
         [u'Burgos', [[u'Aranda de Duero',
            'E1',
            'Z',
            'III'], [u'Burgos ',
            'E1',
            'Z',
            'III'], [u'Miranda de Ebro',
            'D1',
            'Z',
            'III']]],
         [u'C\xe1ceres', [[u'C\xe1ceres ',
            'C4',
            'X',
            'IV'], [u'Plasencia',
            'C4',
            'X',
            'IV']]],
         [u'C\xe1diz', [[u'Algeciras',
            'A3',
            'W',
            'V'],
           [u'Arcos de la Frontera',
            'B3',
            'X',
            'V'],
           [u'Barbate',
            'A3',
            'W',
            'V'],
           [u'C\xe1diz  ',
            'A3',
            'W',
            'V'],
           [u'Chiclana de la Frontera',
            'A3',
            'W',
            'V'],
           [u'Jerez de la Frontera',
            'A3',
            'W',
            'V'],
           [u'La L\xednea de la Concepci\xf3n',
            'A3',
            'W',
            'V'],
           [u'El Puerto de Santa Mar\xeda',
            'A3',
            'W',
            'V'],
           [u'Puerto Real',
            'A3',
            'W',
            'V'],
           [u'Rota ',
            'A3',
            'W',
            'V'],
           [u'San Fernando',
            'A3',
            'W',
            'V'],
           [u'San Roque',
            'A3',
            'W',
            'V'],
           [u'Sanl\xfacar de Barrameda',
            'A3',
            'W',
            'V']]],
         [u'Cantabria', [[u'Camargo',
            'C1',
            'W',
            'I'], [u'Santander',
            'C1',
            'W',
            'I'], [u'Torrelavega',
            'C1',
            'W',
            'I']]],
         [u'Castell\xf3n', [[u'Burriana',
            'B3',
            'W',
            'IV'],
           [u'Castell\xf3n de la Plana',
            'B3',
            'W',
            'IV'],
           [u'La Vall d\xb4Uixo',
            'C3',
            'W',
            'IV'],
           [u'Vila-Real',
            'B3',
            'W',
            'IV'],
           [u'Vinaroz',
            'B3',
            'W',
            'IV']]],
         [u'Ceuta', [[u'Ceuta',
            'B3',
            'W',
            'IV']]],
         [u'Ciudad Real', [[u'Alc\xe1zar de San Juan',
            'D3',
            'Y',
            'V'],
           [u'Ciudad Real ',
            'D3',
            'Y',
            'V'],
           [u'Puertollano',
            'D3',
            'Y',
            'V'],
           [u'Tomelloso',
            'D3',
            'Y',
            'V'],
           [u'Valdepe\xf1as',
            'D3',
            'Y',
            'V']]],
         [u'C\xf3rdoba', [[u'Baena',
            'C4',
            'Y',
            'V'],
           [u'Cabra',
            'C4',
            'Y',
            'V'],
           [u'C\xf3rdoba ',
            'B4',
            'X',
            'V'],
           [u'Lucena',
            'C4',
            'Y',
            'V'],
           [u'Montilla',
            'C4',
            'Y',
            'V'],
           [u'Priego de C\xf3rdoba',
            'D3',
            'Z',
            'V'],
           [u'Puente Genil',
            'C4',
            'X',
            'V']]],
         [u'Cuenca', [[u'Cuenca ',
            'D2',
            'Z',
            'IV'], [u'Taranc\xf3n',
            'D2',
            'Z',
            'IV']]],
         [u'Girona', [[u'Blanes',
            'C2',
            'X',
            'III'],
           [u'Figueres',
            'C2',
            'X',
            'III'],
           [u'Girona ',
            'D2',
            'X',
            'III'],
           [u'Olot',
            'D2',
            'Y',
            'III'],
           [u'Salt',
            'C2',
            'X',
            'III']]],
         [u'Granada', [[u'Almu\xf1ecar',
            'A4',
            'Y',
            'V'],
           [u'Baza',
            'D3',
            'Y',
            'V'],
           [u'Granada ',
            'C3',
            'Y',
            'V'],
           [u'Guadix',
            'D3',
            'Y',
            'V'],
           [u'Loja',
            'C4',
            'Y',
            'V'],
           [u'Motril',
            'A4',
            'Y',
            'V']]],
         [u'Guadalajara', [[u'Azuqueca de Henares',
            'D3',
            'Y',
            'IV'], [u'Guadalajara ',
            'D3',
            'Y',
            'IV'], [u'Molina de Arag\xf3n',
            'E1',
            'Z',
            'IV']]],
         [u'Guip\xfazcoa', [[u'\xc9ibar',
            'D1',
            'W',
            'I'],
           [u'Ir\xfan',
            'D1',
            'W',
            'I'],
           [u'Mondrag\xf3n',
            'D1',
            'X',
            'I'],
           [u'Renter\xeda',
            'D1',
            'W',
            'I'],
           [u'San Sebasti\xe1n',
            'D1',
            'W',
            'I'],
           [u'Zarautz',
            'D1',
            'W',
            'I']]],
         [u'Huelva', [[u'Almonte',
            'B4',
            'W',
            'V'],
           [u'Ayamonte',
            'A4',
            'W',
            'V'],
           [u'Huelva ',
            'A4',
            'W',
            'V'],
           [u'Isla Cristina',
            'A4',
            'W',
            'V'],
           [u'Lepe',
            'A4',
            'W',
            'V']]],
         [u'Huesca', [[u'Barbastro',
            'D3',
            'Y',
            'IV'],
           [u'Fraga',
            'C3',
            'Y',
            'IV'],
           [u'Huesca ',
            'D2',
            'Y',
            'IV'],
           [u'Jaca',
            'E1',
            'Z',
            'IV'],
           [u'Monz\xf3n',
            'D3',
            'Y',
            'IV'],
           [u'Sabi\xf1anigo',
            'E1',
            'Z',
            'IV']]],
         [u'Illes Balears', [[u'Calvi\xe1',
            'B3',
            'W',
            'IV'],
           [u'Ciutadella de Menorca',
            'B3',
            'W',
            'IV'],
           [u'Eivissa',
            'B3',
            'W',
            'IV'],
           [u'Inca',
            'B3',
            'W',
            'IV'],
           [u'Llucmajor',
            'B3',
            'W',
            'IV'],
           [u'Mah\xf3n',
            'B3',
            'W',
            'IV'],
           [u'Manacor',
            'B3',
            'W',
            'IV'],
           [u'Palma de Mallorca',
            'B3',
            'W',
            'IV'],
           [u'Santa Eulalia del R\xedo',
            'B3',
            'W',
            'IV']]],
         [u'Ja\xe9n', [[u'Alcal\xe1 la Real',
            'D3',
            'Y',
            'V'],
           [u'And\xfajar',
            'B4',
            'W',
            'V'],
           [u'Ja\xe9n ',
            'C4',
            'W',
            'V'],
           [u'Linares',
            'C4',
            'W',
            'V'],
           [u'Martos ',
            'D3',
            'X',
            'V'],
           [u'\xdabeda',
            'C4',
            'X',
            'V']]],
         [u'La Rioja', [[u'Alfaro',
            'D2',
            'X',
            'III'],
           [u'Arnedo',
            'D2',
            'X',
            'III'],
           [u'Calahorra',
            'D2',
            'X',
            'III'],
           [u'Haro',
            'D2',
            'X',
            'III'],
           [u'Logro\xf1o',
            'D2',
            'X',
            'III'],
           [u'Santo Domingo de la Calzada',
            'D2',
            'Y',
            'III']]],
         [u'Las Palmas', [[u'Arrecife',
            'alpha3',
            'V',
            'V'],
           [u'Arucas',
            'alpha3',
            'V',
            'V'],
           [u'Galdar',
            'alpha3',
            'V',
            'V'],
           [u'Ingenio',
            'alpha3',
            'V',
            'V'],
           [u'Las Palmas de Gran Canaria',
            'alpha3',
            'V',
            'V'],
           [u'San Bartolom\xe9 de Tirajana',
            'B2',
            'V',
            'V'],
           [u'Santa Luc\xeda',
            'A2',
            'V',
            'V'],
           [u'Telde',
            'alpha3',
            'V',
            'V']]],
         [u'Le\xf3n', [[u'Le\xf3n ',
            'E1',
            'Z',
            'III'], [u'Ponferrada',
            'E1',
            'Z',
            'III'], [u'San Andr\xe9s del Rabanedo',
            'E1',
            'Z',
            'III']]],
         [u'Lugo', [[u'Lugo ',
            'D1',
            'X',
            'II'], [u'Monforte de Lemos',
            'D1',
            'X',
            'II'], [u'Viveiro',
            'D1',
            'X',
            'II']]],
         [u'Lleida', [[u'Balaguer',
            'D3',
            'Y',
            'IV'], [u'L\xe9rida',
            'D3',
            'Y',
            'IV'], [u'La Seu d\xb4Urgell',
            'E1',
            'Z',
            'IV']]],
         [u'Madrid', [[u'Alcal\xe1 de Henares',
            'D3',
            'Y',
            'IV'],
           [u'Alcobendas',
            'D3',
            'Y',
            'IV'],
           [u'Alcorc\xf3n',
            'D3',
            'Y',
            'IV'],
           [u'Aranjuez',
            'C3',
            'Y',
            'IV'],
           [u'Arganda de Rey',
            'D3',
            'Y',
            'IV'],
           [u'Colmenar Viejo',
            'D3',
            'Z',
            'IV'],
           [u'Collado Villalba',
            'D3',
            'Z',
            'IV'],
           [u'Coslada',
            'D3',
            'Y',
            'IV'],
           [u'Fuenlabrada',
            'D3',
            'Y',
            'IV'],
           [u'Getafe',
            'D3',
            'Y',
            'IV'],
           [u'Legan\xe9s',
            'D3',
            'Y',
            'IV'],
           [u'Madrid ',
            'D3',
            'Y',
            'IV'],
           [u'Majadahonda',
            'D3',
            'Y',
            'IV'],
           [u'M\xf3stoles',
            'D3',
            'Y',
            'IV'],
           [u'Parla',
            'D3',
            'Y',
            'IV'],
           [u'Pinto',
            'D3',
            'Y',
            'IV'],
           [u'Pozuelo de Alarc\xf3n',
            'D3',
            'Y',
            'IV'],
           [u'Rivas-Vaciamadrid',
            'D3',
            'Y',
            'IV'],
           [u'Las Rozas de Madrid',
            'D3',
            'Y',
            'IV'],
           [u'San Fernando de Henares',
            'D3',
            'Y',
            'IV'],
           [u'San Sebasti\xe1n de los Reyes',
            'D3',
            'Y',
            'IV'],
           [u'Torrej\xf3n de Ardoz',
            'D3',
            'Y',
            'IV'],
           [u'Tres Cantos',
            'D3',
            'Y',
            'IV'],
           [u'Valdemoro',
            'D3',
            'Y',
            'IV']]],
         [u'M\xe1laga', [[u'Antequera',
            'C3',
            'Y',
            'V'],
           [u'Benalm\xe1dena',
            'B3',
            'X',
            'V'],
           [u'Estepona',
            'A3',
            'W',
            'V'],
           [u'Fuengirola',
            'A3',
            'W',
            'V'],
           [u'M\xe1laga ',
            'A3',
            'W',
            'V'],
           [u'Marbella',
            'A3',
            'W',
            'V'],
           [u'Mijas',
            'C3',
            'Y',
            'V'],
           [u'Rinc\xf3n de la Victoria',
            'A3',
            'W',
            'V'],
           [u'Ronda',
            'D3',
            'Y',
            'V'],
           [u'Torremolinos',
            'A3',
            'W',
            'V'],
           [u'V\xe9lez-M\xe1laga',
            'A3',
            'W',
            'V']]],
         [u'Melilla', [[u'Melilla ',
            'A3',
            'W',
            'V']]],
         [u'Murcia', [[u'\xc1guilas',
            'B3',
            'W',
            'V'],
           [u'Alcantarilla',
            'B3',
            'W',
            'V'],
           [u'Caravaca de la Cruz',
            'D3',
            'Z',
            'V'],
           [u'Cartagena',
            'B3',
            'W',
            'V'],
           [u'Cieza',
            'C3',
            'W',
            'V'],
           [u'Jumilla',
            'C3',
            'Y',
            'V'],
           [u'Lorca',
            'C3',
            'X',
            'V'],
           [u'Molina de Segura',
            'B3',
            'W',
            'V'],
           [u'Murcia ',
            'B3',
            'W',
            'V'],
           [u'Torre-Pacheco',
            'B3',
            'W',
            'V'],
           [u'Totana',
            'C3',
            'X',
            'V'],
           [u'Yecla',
            'D3',
            'Y',
            'V']]],
         [u'Navarra', [[u'Alsasua',
            'D1',
            'Y',
            'II'],
           [u'Bara\xf1\xe1in',
            'D1',
            'Y',
            'II'],
           [u'Vera de Bidasoa',
            'C2',
            'Y',
            'II'],
           [u'Olite',
            'D1',
            'Y',
            'II'],
           [u'Pamplona',
            'D1',
            'Y',
            'II'],
           [u'Sang\xfcesa',
            'D1',
            'Y',
            'II'],
           [u'Tudela',
            'D2',
            'Y',
            'II']]],
         [u'Ourense', [[u'A R\xfaa',
            'D2',
            'X',
            'II'],
           [u'O Barco de Valdeorras',
            'D2',
            'X',
            'II'],
           [u'Ourense ',
            'D2',
            'X',
            'II'],
           [u'Ver\xedn',
            'D2',
            'X',
            'II']]],
         [u'Palencia', [[u'Aguilar de Campoo',
            'E1',
            'Y',
            'IV'],
           [u'Guardo',
            'E1',
            'Z',
            'IV'],
           [u'Herrera de Pisuerga',
            'E1',
            'Y',
            'IV'],
           [u'Palencia ',
            'D1',
            'Y',
            'IV'],
           [u'Salda\xf1a',
            'E1',
            'Z',
            'IV']]],
         [u'Pontevedra', [[u'Cangas',
            'C1',
            'W',
            'II'],
           [u'A Estrada',
            'C1',
            'W',
            'II'],
           [u'Lal\xedn',
            'D1',
            'X',
            'II'],
           [u'Mar\xedn',
            'C1',
            'W',
            'II'],
           [u'Pontevedra ',
            'C1',
            'W',
            'II'],
           [u'Redondela',
            'C1',
            'W',
            'II'],
           [u'Vigo',
            'C1',
            'W',
            'II'],
           [u'Vilagarc\xeda de Arousa',
            'C1',
            'W',
            'II']]],
         [u'Salamanca', [[u'B\xe9jar',
            'E1',
            'Z',
            'IV'],
           [u'Ciudad Rodrigo',
            'D2',
            'Z',
            'IV'],
           [u'Pe\xf1aranda de Bracamonte',
            'E1',
            'Z',
            'IV'],
           [u'Salamanca ',
            'D2',
            'Z',
            'IV'],
           [u'Vitigudino',
            'D2',
            'Z',
            'IV']]],
         [u'Santa Cruz de Tenerife', [[u'Arona',
            'A2',
            'V',
            'V'],
           [u'Icod de los Vinos',
            'alpha3',
            'V',
            'V'],
           [u'La Orotava',
            'alpha3',
            'V',
            'V'],
           [u'Puerto de la Cruz',
            'alpha3',
            'V',
            'V'],
           [u'Los Realejos',
            'alpha3',
            'V',
            'V'],
           [u'San Crist\xf3bal de la Laguna',
            'A2',
            'V',
            'V'],
           [u'Santa Cruz de Tenerife',
            'alpha3',
            'V',
            'V'],
           [u'Tacoronte',
            'A2',
            'V',
            'V']]],
         [u'Segovia', [[u'Cu\xe9llar',
            'D2',
            'Z',
            'III'],
           [u'El Espinar',
            'E1',
            'Z',
            'III'],
           [u'San Ildefonso',
            'E1',
            'Z',
            'III'],
           [u'Segovia ',
            'D2',
            'Z',
            'III']]],
         [u'Sevilla', [[u'Alcal\xe1 de Guadaira',
            'B4',
            'W',
            'V'],
           [u'Camas',
            'B4',
            'W',
            'V'],
           [u'Carmona',
            'C4',
            'X',
            'V'],
           [u'Coria del R\xedo',
            'B4',
            'W',
            'V'],
           [u'Dos Hermanas',
            'B4',
            'W',
            'V'],
           [u'\xc9cija',
            'B4',
            'W',
            'V'],
           [u'Lebrija',
            'B4',
            'W',
            'V'],
           [u'Mairena del Aljarafe',
            'B4',
            'W',
            'V'],
           [u'Mor\xf3n de la Frontera',
            'C4',
            'X',
            'V'],
           [u'Los Palacios y Villafranca',
            'B4',
            'W',
            'V'],
           [u'La Rinconada',
            'B4',
            'W',
            'V'],
           [u'San Juan de Aznalfarache',
            'B4',
            'W',
            'V'],
           [u'Sevilla ',
            'B4',
            'W',
            'V'],
           [u'Utrera',
            'B4',
            'W',
            'V']]],
         [u'Soria', [[u'\xc1greda',
            'E1',
            'Z',
            'III'],
           [u'Almaz\xe1n',
            'E1',
            'Z',
            'III'],
           [u'Burgo de Osma',
            'E1',
            'Z',
            'III'],
           [u'San Leonardo de Yag\xfce',
            'E1',
            'Z',
            'III'],
           [u'Soria ',
            'E1',
            'Z',
            'III']]],
         [u'Tarragona', [[u'Reus',
            'C3',
            'W',
            'IV'],
           [u'Tarragona ',
            'B3',
            'W',
            'IV'],
           [u'Tortosa',
            'B3',
            'W',
            'IV'],
           [u'Valls',
            'C3',
            'X',
            'IV'],
           [u'El Vendrell',
            'C3',
            'W',
            'IV']]],
         [u'Teruel', [[u'Alca\xf1iz',
            'C3',
            'Z',
            'IV'],
           [u'Andorra',
            'D2',
            'Z',
            'IV'],
           [u'Calamocha',
            'D2',
            'Z',
            'IV'],
           [u'Calanda',
            'C2',
            'Z',
            'IV'],
           [u'Teruel ',
            'D2',
            'Z',
            'IV']]],
         [u'Toledo', [[u'Illescas',
            'D3',
            'X',
            'V'],
           [u'Sese\xf1a',
            'D3',
            'X',
            'V'],
           [u'Talavera de la Reina',
            'C4',
            'X',
            'V'],
           [u'Toledo ',
            'C4',
            'X',
            'V'],
           [u'Torrijos',
            'D3',
            'X',
            'V']]],
         [u'Valencia', [[u'Alaqu\xe0s',
            'B3',
            'W',
            'IV'],
           [u'Aldaia',
            'B3',
            'W',
            'IV'],
           [u'Algemes\xed',
            'B3',
            'W',
            'IV'],
           [u'Alzira',
            'B3',
            'W',
            'IV'],
           [u'Burjassot',
            'B3',
            'W',
            'IV'],
           [u'Carcaixent',
            'B3',
            'W',
            'IV'],
           [u'Catarroja',
            'B3',
            'W',
            'IV'],
           [u'Cullera',
            'B3',
            'W',
            'IV'],
           [u'Gand\xeda',
            'B3',
            'W',
            'IV'],
           [u'Manises',
            'C3',
            'W',
            'IV'],
           [u'Mislata',
            'B3',
            'W',
            'IV'],
           [u'Oliva',
            'B3',
            'W',
            'IV'],
           [u'Ontinyent',
            'C3',
            'X',
            'IV'],
           [u'Paterna',
            'C3',
            'W',
            'IV'],
           [u'Quart de Poblet',
            'B3',
            'W',
            'IV'],
           [u'Sagunto',
            'B3',
            'W',
            'IV'],
           [u'Sueca',
            'B3',
            'W',
            'IV'],
           [u'Torrent',
            'B3',
            'W',
            'IV'],
           [u'Valencia ',
            'B3',
            'W',
            'IV'],
           [u'X\xe1tiva',
            'C3',
            'W',
            'IV'],
           [u'Xirivella',
            'B3',
            'W',
            'IV']]],
         [u'Valladolid', [[u'Arroyo de la Encomienda',
            'D2',
            'Y',
            'IV'],
           [u'Laguna de Duero',
            'D2',
            'Y',
            'IV'],
           [u'Medina del Campo',
            'D2',
            'Y',
            'IV'],
           [u'Tordesillas',
            'D2',
            'Y',
            'IV'],
           [u'Valladolid ',
            'D2',
            'Y',
            'IV']]],
         [u'Vizcaya', [[u'Barakaldo',
            'C1',
            'W',
            'I'],
           [u'Basauri',
            'C1',
            'W',
            'I'],
           [u'Bilbao',
            'C1',
            'W',
            'I'],
           [u'Durango',
            'C1',
            'W',
            'I'],
           [u'Erandio',
            'C1',
            'W',
            'I'],
           [u'Galdakao',
            'C1',
            'W',
            'I'],
           [u'Getxo',
            'C1',
            'W',
            'I'],
           [u'Leioa',
            'C1',
            'W',
            'I'],
           [u'Portugalete',
            'C1',
            'W',
            'I'],
           [u'Santurtzi',
            'C1',
            'W',
            'I'],
           [u'Sestao',
            'C1',
            'W',
            'I']]],
         [u'Zamora', [[u'Benavente',
            'D2',
            'Y',
            'IV'],
           [u'Puebla de Sanabria',
            'E1',
            'Z',
            'IV'],
           [u'Toro',
            'D2',
            'Y',
            'IV'],
           [u'Villalpando',
            'D2',
            'Y',
            'IV'],
           [u'Zamora ',
            'D2',
            'Y',
            'IV']]],
         [u'Zaragoza', [[u'Calatayud',
            'D3',
            'Y',
            'IV'],
           [u'Ejea de los Caballeros',
            'D3',
            'Y',
            'IV'],
           [u'Tarazona',
            'D3',
            'Y',
            'IV'],
           [u'Utebo',
            'D3',
            'Y',
            'IV'],
           [u'Zaragoza',
            'D3',
            'Y',
            'IV']]]]
        self.listadoLocalidades = [(u'Arteixo', _(u'Arteixo')),
         (u'Carballo', _(u'Carballo')),
         (u'A Coru\xf1a', _(u'A Coru\xf1a')),
         (u'Ferrol', _(u'Ferrol')),
         (u'Nar\xf3n', _(u'Nar\xf3n')),
         (u'Oleiros', _(u'Oleiros')),
         (u'Ribeira', _(u'Ribeira')),
         (u'Santiago de Compostela', _(u'Santiago de Compostela')),
         (u'Amurrio', _(u'Amurrio')),
         (u'Llodio', _(u'Llodio')),
         (u'Salvatierra', _(u'Salvatierra')),
         (u'Vitoria-Gasteiz', _(u'Vitoria-Gasteiz')),
         (u'Albacete ', _(u'Albacete ')),
         (u'Almansa', _(u'Almansa')),
         (u'Hellin', _(u'Hellin')),
         (u'Villarrobledo', _(u'Villarrobledo')),
         (u'Alcoy', _(u'Alcoy')),
         (u'Alicante ', _(u'Alicante ')),
         (u'Benidorm', _(u'Benidorm')),
         (u'Crevillent', _(u'Crevillent')),
         (u'D\xe9nia', _(u'D\xe9nia')),
         (u'Elche', _(u'Elche')),
         (u'Elda', _(u'Elda')),
         (u'Ibi', _(u'Ibi')),
         (u'J\xe1vea', _(u'J\xe1vea')),
         (u'Novelda', _(u'Novelda')),
         (u'Orihuela', _(u'Orihuela')),
         (u'Petrer', _(u'Petrer')),
         (u'San Vicente del Raspeig', _(u'San Vicente del Raspeig')),
         (u'Torrevieja', _(u'Torrevieja')),
         (u'Villajoyosa', _(u'Villajoyosa')),
         (u'Villena', _(u'Villena')),
         (u'Adra', _(u'Adra')),
         (u'Almer\xeda ', _(u'Almer\xeda ')),
         (u'El Ejido', _(u'El Ejido')),
         (u'Roquetas de mar', _(u'Roquetas de mar')),
         (u'Avil\xe9s', _(u'Avil\xe9s')),
         (u'Castrill\xf3n', _(u'Castrill\xf3n')),
         (u'Gij\xf3n', _(u'Gij\xf3n')),
         (u'Langreo', _(u'Langreo')),
         (u'Mieres', _(u'Mieres')),
         (u'Oviedo', _(u'Oviedo')),
         (u'San Mart\xedn del Rey Aurelio', _(u'San Mart\xedn del Rey Aurelio')),
         (u'Siero', _(u'Siero')),
         (u'Arenas de San Pedro', _(u'Arenas de San Pedro')),
         (u'Ar\xe9valo', _(u'Ar\xe9valo')),
         (u'\xc1vila ', _(u'\xc1vila ')),
         (u'El Barraco', _(u'El Barraco')),
         (u'Las Navas del Marqu\xe9s', _(u'Las Navas del Marqu\xe9s')),
         (u'Almendralejo', _(u'Almendralejo')),
         (u'Badajoz ', _(u'Badajoz ')),
         (u'Don Benito', _(u'Don Benito')),
         (u'M\xe9rida', _(u'M\xe9rida')),
         (u'Villanueva de la Serena', _(u'Villanueva de la Serena')),
         (u'Badalona', _(u'Badalona')),
         (u'Barber\xe1 del Vall\xe9s', _(u'Barber\xe1 del Vall\xe9s')),
         (u'Barcelona ', _(u'Barcelona ')),
         (u'Castelldefels', _(u'Castelldefels')),
         (u'Cerdanyola del Valles', _(u'Cerdanyola del Valles')),
         (u'Cornell\xe1 de Llobregat', _(u'Cornell\xe1 de Llobregat')),
         (u'Gav\xe1', _(u'Gav\xe1')),
         (u'Granollers', _(u'Granollers')),
         (u'L\xb4Hospitalet de Llobregat', _(u'L\xb4Hospitalet de Llobregat')),
         (u'Igualada', _(u'Igualada')),
         (u'Manresa', _(u'Manresa')),
         (u'El Masnou', _(u'El Masnou')),
         (u'Matar\xf3', _(u'Matar\xf3')),
         (u'Mollet del Vall\xe9s', _(u'Mollet del Vall\xe9s')),
         (u'Moncada i Reixach', _(u'Moncada i Reixach')),
         (u'El Prat de Llobregat', _(u'El Prat de Llobregat')),
         (u'Premia de Mar', _(u'Premia de Mar')),
         (u'Ripollet', _(u'Ripollet')),
         (u'Rub\xed', _(u'Rub\xed')),
         (u'Sabadell', _(u'Sabadell')),
         (u'Sant Adri\xe1 de Bes\xf3s', _(u'Sant Adri\xe1 de Bes\xf3s')),
         (u'Sant Boi de Llobregat', _(u'Sant Boi de Llobregat')),
         (u'Sant Cugat del Vall\xe9s', _(u'Sant Cugat del Vall\xe9s')),
         (u'Sant Feli\xfa de Llobregat', _(u'Sant Feli\xfa de Llobregat')),
         (u'Mollet del Vall\xe9s', _(u'Mollet del Vall\xe9s')),
         (u'Sant Joan Desp\xed', _(u'Sant Joan Desp\xed')),
         (u'Sant Pere de Ribes', _(u'Sant Pere de Ribes')),
         (u'Sant Vicen\xe7 dels Horts', _(u'Sant Vicen\xe7 dels Horts')),
         (u'Santa Coloma de Gramanet', _(u'Santa Coloma de Gramanet')),
         (u'Terrasa', _(u'Terrasa')),
         (u'Vic', _(u'Vic')),
         (u'Viladecans', _(u'Viladecans')),
         (u'Vilafranca del Pened\xe9s', _(u'Vilafranca del Pened\xe9s')),
         (u'Vilanova i la Geltr\xfa', _(u'Vilanova i la Geltr\xfa')),
         (u'Aranda de Duero', _(u'Aranda de Duero')),
         (u'Burgos ', _(u'Burgos ')),
         (u'Miranda de Ebro', _(u'Miranda de Ebro')),
         (u'C\xe1ceres ', _(u'C\xe1ceres ')),
         (u'Plasencia', _(u'Plasencia')),
         (u'Algeciras', _(u'Algeciras')),
         (u'Arcos de la Frontera', _(u'Arcos de la Frontera')),
         (u'Barbate', _(u'Barbate')),
         (u'C\xe1diz  ', _(u'C\xe1diz  ')),
         (u'Chiclana de la Frontera', _(u'Chiclana de la Frontera')),
         (u'Jerez de la Frontera', _(u'Jerez de la Frontera')),
         (u'La L\xednea de la Concepci\xf3n', _(u'La L\xednea de la Concepci\xf3n')),
         (u'El Puerto de Santa Mar\xeda', _(u'El Puerto de Santa Mar\xeda')),
         (u'Puerto Real', _(u'Puerto Real')),
         (u'Rota ', _(u'Rota ')),
         (u'San Fernando', _(u'San Fernando')),
         (u'San Roque', _(u'San Roque')),
         (u'Sanl\xfacar de Barrameda', _(u'Sanl\xfacar de Barrameda')),
         (u'Camargo', _(u'Camargo')),
         (u'Santander', _(u'Santander')),
         (u'Torrelavega', _(u'Torrelavega')),
         (u'Burriana', _(u'Burriana')),
         (u'Castell\xf3n de la Plana', _(u'Castell\xf3n de la Plana')),
         (u'La Vall d\xb4Uixo', _(u'La Vall d\xb4Uixo')),
         (u'Vila-Real', _(u'Vila-Real')),
         (u'Vinaroz', _(u'Vinaroz')),
         (u'Ceuta', _(u'Ceuta')),
         (u'Alc\xe1zar de San Juan', _(u'Alc\xe1zar de San Juan')),
         (u'Ciudad Real ', _(u'Ciudad Real ')),
         (u'Puertollano', _(u'Puertollano')),
         (u'Tomelloso', _(u'Tomelloso')),
         (u'Valdepe\xf1as', _(u'Valdepe\xf1as')),
         (u'Baena', _(u'Baena')),
         (u'Cabra', _(u'Cabra')),
         (u'C\xf3rdoba ', _(u'C\xf3rdoba ')),
         (u'Lucena', _(u'Lucena')),
         (u'Montilla', _(u'Montilla')),
         (u'Priego de C\xf3rdoba', _(u'Priego de C\xf3rdoba')),
         (u'Puente Genil', _(u'Puente Genil')),
         (u'Cuenca ', _(u'Cuenca ')),
         (u'Taranc\xf3n', _(u'Taranc\xf3n')),
         (u'Blanes', _(u'Blanes')),
         (u'Figueres', _(u'Figueres')),
         (u'Girona ', _(u'Girona ')),
         (u'Olot', _(u'Olot')),
         (u'Salt', _(u'Salt')),
         (u'Almu\xf1ecar', _(u'Almu\xf1ecar')),
         (u'Baza', _(u'Baza')),
         (u'Granada ', _(u'Granada ')),
         (u'Guadix', _(u'Guadix')),
         (u'Loja', _(u'Loja')),
         (u'Motril', _(u'Motril')),
         (u'Azuqueca de Henares', _(u'Azuqueca de Henares')),
         (u'Guadalajara ', _(u'Guadalajara ')),
         (u'Molina de Arag\xf3n', _(u'Molina de Arag\xf3n')),
         (u'\xc9ibar', _(u'\xc9ibar')),
         (u'Ir\xfan', _(u'Ir\xfan')),
         (u'Mondrag\xf3n', _(u'Mondrag\xf3n')),
         (u'Renter\xeda', _(u'Renter\xeda')),
         (u'San Sebasti\xe1n', _(u'San Sebasti\xe1n')),
         (u'Zarautz', _(u'Zarautz')),
         (u'Almonte', _(u'Almonte')),
         (u'Ayamonte', _(u'Ayamonte')),
         (u'Huelva ', _(u'Huelva ')),
         (u'Isla Cristina', _(u'Isla Cristina')),
         (u'Lepe', _(u'Lepe')),
         (u'Barbastro', _(u'Barbastro')),
         (u'Fraga', _(u'Fraga')),
         (u'Huesca ', _(u'Huesca ')),
         (u'Jaca', _(u'Jaca')),
         (u'Monz\xf3n', _(u'Monz\xf3n')),
         (u'Sabi\xf1anigo', _(u'Sabi\xf1anigo')),
         (u'Calvi\xe1', _(u'Calvi\xe1')),
         (u'Ciutadella de Menorca', _(u'Ciutadella de Menorca')),
         (u'Eivissa', _(u'Eivissa')),
         (u'Inca', _(u'Inca')),
         (u'Llucmajor', _(u'Llucmajor')),
         (u'Mah\xf3n', _(u'Mah\xf3n')),
         (u'Manacor', _(u'Manacor')),
         (u'Palma de Mallorca', _(u'Palma de Mallorca')),
         (u'Santa Eulalia del R\xedo', _(u'Santa Eulalia del R\xedo')),
         (u'Alcal\xe1 la Real', _(u'Alcal\xe1 la Real')),
         (u'And\xfajar', _(u'And\xfajar')),
         (u'Ja\xe9n ', _(u'Ja\xe9n ')),
         (u'Linares', _(u'Linares')),
         (u'Martos ', _(u'Martos ')),
         (u'\xdabeda', _(u'\xdabeda')),
         (u'Alfaro', _(u'Alfaro')),
         (u'Arnedo', _(u'Arnedo')),
         (u'Calahorra', _(u'Calahorra')),
         (u'Haro', _(u'Haro')),
         (u'Logro\xf1o', _(u'Logro\xf1o')),
         (u'Santo Domingo de la Calzada', _(u'Santo Domingo de la Calzada')),
         (u'Arrecife', _(u'Arrecife')),
         (u'Arucas', _(u'Arucas')),
         (u'Galdar', _(u'Galdar')),
         (u'Ingenio', _(u'Ingenio')),
         (u'Las Palmas de Gran Canaria', _(u'Las Palmas de Gran Canaria')),
         (u'San Bartolom\xe9 de Tirajana', _(u'San Bartolom\xe9 de Tirajana')),
         (u'Santa Luc\xeda', _(u'Santa Luc\xeda')),
         (u'Telde', _(u'Telde')),
         (u'Le\xf3n ', _(u'Le\xf3n ')),
         (u'Ponferrada', _(u'Ponferrada')),
         (u'San Andr\xe9s del Rabanedo', _(u'San Andr\xe9s del Rabanedo')),
         (u'Lugo ', _(u'Lugo ')),
         (u'Monforte de Lemos', _(u'Monforte de Lemos')),
         (u'Viveiro', _(u'Viveiro')),
         (u'Balaguer', _(u'Balaguer')),
         (u'L\xe9rida', _(u'L\xe9rida')),
         (u'La Seu d\xb4Urgell', _(u'La Seu d\xb4Urgell')),
         (u'Alcal\xe1 de Henares', _(u'Alcal\xe1 de Henares')),
         (u'Alcobendas', _(u'Alcobendas')),
         (u'Alcorc\xf3n', _(u'Alcorc\xf3n')),
         (u'Aranjuez', _(u'Aranjuez')),
         (u'Arganda de Rey', _(u'Arganda de Rey')),
         (u'Colmenar Viejo', _(u'Colmenar Viejo')),
         (u'Collado Villalba', _(u'Collado Villalba')),
         (u'Coslada', _(u'Coslada')),
         (u'Fuenlabrada', _(u'Fuenlabrada')),
         (u'Getafe', _(u'Getafe')),
         (u'Legan\xe9s', _(u'Legan\xe9s')),
         (u'Madrid ', _(u'Madrid ')),
         (u'Majadahonda', _(u'Majadahonda')),
         (u'M\xf3stoles', _(u'M\xf3stoles')),
         (u'Parla', _(u'Parla')),
         (u'Pinto', _(u'Pinto')),
         (u'Pozuelo de Alarc\xf3n', _(u'Pozuelo de Alarc\xf3n')),
         (u'Rivas-Vaciamadrid', _(u'Rivas-Vaciamadrid')),
         (u'Las Rozas de Madrid', _(u'Las Rozas de Madrid')),
         (u'San Fernando de Henares', _(u'San Fernando de Henares')),
         (u'San Sebasti\xe1n de los Reyes', _(u'San Sebasti\xe1n de los Reyes')),
         (u'Torrej\xf3n de Ardoz', _(u'Torrej\xf3n de Ardoz')),
         (u'Tres Cantos', _(u'Tres Cantos')),
         (u'Valdemoro', _(u'Valdemoro')),
         (u'Antequera', _(u'Antequera')),
         (u'Benalm\xe1dena', _(u'Benalm\xe1dena')),
         (u'Estepona', _(u'Estepona')),
         (u'Fuengirola', _(u'Fuengirola')),
         (u'M\xe1laga ', _(u'M\xe1laga ')),
         (u'Marbella', _(u'Marbella')),
         (u'Mijas', _(u'Mijas')),
         (u'Rinc\xf3n de la Victoria', _(u'Rinc\xf3n de la Victoria')),
         (u'Ronda', _(u'Ronda')),
         (u'Torremolinos', _(u'Torremolinos')),
         (u'V\xe9lez-M\xe1laga', _(u'V\xe9lez-M\xe1laga')),
         (u'Melilla ', _(u'Melilla ')),
         (u'\xc1guilas', _(u'\xc1guilas')),
         (u'Alcantarilla', _(u'Alcantarilla')),
         (u'Caravaca de la Cruz', _(u'Caravaca de la Cruz')),
         (u'Cartagena', _(u'Cartagena')),
         (u'Cieza', _(u'Cieza')),
         (u'Jumilla', _(u'Jumilla')),
         (u'Lorca', _(u'Lorca')),
         (u'Molina de Segura', _(u'Molina de Segura')),
         (u'Murcia ', _(u'Murcia ')),
         (u'Torre-Pacheco', _(u'Torre-Pacheco')),
         (u'Totana', _(u'Totana')),
         (u'Yecla', _(u'Yecla')),
         (u'Alsasua', _(u'Alsasua')),
         (u'Bara\xf1\xe1in', _(u'Bara\xf1\xe1in')),
         (u'Vera de Bidasoa', _(u'Vera de Bidasoa')),
         (u'Olite', _(u'Olite')),
         (u'Pamplona', _(u'Pamplona')),
         (u'Sang\xfcesa', _(u'Sang\xfcesa')),
         (u'Tudela', _(u'Tudela')),
         (u'A R\xfaa', _(u'A R\xfaa')),
         (u'O Barco de Valdeorras', _(u'O Barco de Valdeorras')),
         (u'Ourense ', _(u'Ourense ')),
         (u'Ver\xedn', _(u'Ver\xedn')),
         (u'Aguilar de Campoo', _(u'Aguilar de Campoo')),
         (u'Guardo', _(u'Guardo')),
         (u'Herrera de Pisuerga', _(u'Herrera de Pisuerga')),
         (u'Palencia ', _(u'Palencia ')),
         (u'Salda\xf1a', _(u'Salda\xf1a')),
         (u'Cangas', _(u'Cangas')),
         (u'A Estrada', _(u'A Estrada')),
         (u'Lal\xedn', _(u'Lal\xedn')),
         (u'Mar\xedn', _(u'Mar\xedn')),
         (u'Pontevedra ', _(u'Pontevedra ')),
         (u'Redondela', _(u'Redondela')),
         (u'Vigo', _(u'Vigo')),
         (u'Vilagarc\xeda de Arousa', _(u'Vilagarc\xeda de Arousa')),
         (u'B\xe9jar', _(u'B\xe9jar')),
         (u'Ciudad Rodrigo', _(u'Ciudad Rodrigo')),
         (u'Pe\xf1aranda de Bracamonte', _(u'Pe\xf1aranda de Bracamonte')),
         (u'Salamanca ', _(u'Salamanca ')),
         (u'Vitigudino', _(u'Vitigudino')),
         (u'Arona', _(u'Arona')),
         (u'Icod de los Vinos', _(u'Icod de los Vinos')),
         (u'La Orotava', _(u'La Orotava')),
         (u'Puerto de la Cruz', _(u'Puerto de la Cruz')),
         (u'Los Realejos', _(u'Los Realejos')),
         (u'San Crist\xf3bal de la Laguna', _(u'San Crist\xf3bal de la Laguna')),
         (u'Santa Cruz de Tenerife', _(u'Santa Cruz de Tenerife')),
         (u'Tacoronte', _(u'Tacoronte')),
         (u'Cu\xe9llar', _(u'Cu\xe9llar')),
         (u'El Espinar', _(u'El Espinar')),
         (u'San Ildefonso', _(u'San Ildefonso')),
         (u'Segovia ', _(u'Segovia ')),
         (u'Alcal\xe1 de Guadaira', _(u'Alcal\xe1 de Guadaira')),
         (u'Camas', _(u'Camas')),
         (u'Carmona', _(u'Carmona')),
         (u'Coria del R\xedo', _(u'Coria del R\xedo')),
         (u'Dos Hermanas', _(u'Dos Hermanas')),
         (u'\xc9cija', _(u'\xc9cija')),
         (u'Lebrija', _(u'Lebrija')),
         (u'Mairena del Aljarafe', _(u'Mairena del Aljarafe')),
         (u'Mor\xf3n de la Frontera', _(u'Mor\xf3n de la Frontera')),
         (u'Los Palacios y Villafranca', _(u'Los Palacios y Villafranca')),
         (u'La Rinconada', _(u'La Rinconada')),
         (u'San Juan de Aznalfarache', _(u'San Juan de Aznalfarache')),
         (u'Sevilla ', _(u'Sevilla ')),
         (u'Utrera', _(u'Utrera')),
         (u'\xc1greda', _(u'\xc1greda')),
         (u'Almaz\xe1n', _(u'Almaz\xe1n')),
         (u'Burgo de Osma', _(u'Burgo de Osma')),
         (u'San Leonardo de Yag\xfce', _(u'San Leonardo de Yag\xfce')),
         (u'Soria ', _(u'Soria ')),
         (u'Reus', _(u'Reus')),
         (u'Tarragona ', _(u'Tarragona ')),
         (u'Tortosa', _(u'Tortosa')),
         (u'Valls', _(u'Valls')),
         (u'El Vendrell', _(u'El Vendrell')),
         (u'Alca\xf1iz', _(u'Alca\xf1iz')),
         (u'Andorra', _(u'Andorra')),
         (u'Calamocha', _(u'Calamocha')),
         (u'Calanda', _(u'Calanda')),
         (u'Teruel ', _(u'Teruel ')),
         (u'Illescas', _(u'Illescas')),
         (u'Sese\xf1a', _(u'Sese\xf1a')),
         (u'Talavera de la Reina', _(u'Talavera de la Reina')),
         (u'Toledo ', _(u'Toledo ')),
         (u'Torrijos', _(u'Torrijos')),
         (u'Alaqu\xe0s', _(u'Alaqu\xe0s')),
         (u'Aldaia', _(u'Aldaia')),
         (u'Algemes\xed', _(u'Algemes\xed')),
         (u'Alzira', _(u'Alzira')),
         (u'Burjassot', _(u'Burjassot')),
         (u'Carcaixent', _(u'Carcaixent')),
         (u'Catarroja', _(u'Catarroja')),
         (u'Cullera', _(u'Cullera')),
         (u'Gand\xeda', _(u'Gand\xeda')),
         (u'Manises', _(u'Manises')),
         (u'Mislata', _(u'Mislata')),
         (u'Oliva', _(u'Oliva')),
         (u'Ontinyent', _(u'Ontinyent')),
         (u'Paterna', _(u'Paterna')),
         (u'Quart de Poblet', _(u'Quart de Poblet')),
         (u'Sagunto', _(u'Sagunto')),
         (u'Sueca', _(u'Sueca')),
         (u'Torrent', _(u'Torrent')),
         (u'Valencia ', _(u'Valencia ')),
         (u'X\xe1tiva', _(u'X\xe1tiva')),
         (u'Xirivella', _(u'Xirivella')),
         (u'Arroyo de la Encomienda', _(u'Arroyo de la Encomienda')),
         (u'Laguna de Duero', _(u'Laguna de Duero')),
         (u'Medina del Campo', _(u'Medina del Campo')),
         (u'Tordesillas', _(u'Tordesillas')),
         (u'Valladolid ', _(u'Valladolid ')),
         (u'Barakaldo', _(u'Barakaldo')),
         (u'Basauri', _(u'Basauri')),
         (u'Bilbao', _(u'Bilbao')),
         (u'Durango', _(u'Durango')),
         (u'Erandio', _(u'Erandio')),
         (u'Galdakao', _(u'Galdakao')),
         (u'Getxo', _(u'Getxo')),
         (u'Leioa', _(u'Leioa')),
         (u'Portugalete', _(u'Portugalete')),
         (u'Santurtzi', _(u'Santurtzi')),
         (u'Sestao', _(u'Sestao')),
         (u'Benavente', _(u'Benavente')),
         (u'Puebla de Sanabria', _(u'Puebla de Sanabria')),
         (u'Toro', _(u'Toro')),
         (u'Villalpando', _(u'Villalpando')),
         (u'Zamora ', _(u'Zamora ')),
         (u'Calatayud', _(u'Calatayud')),
         (u'Ejea de los Caballeros', _(u'Ejea de los Caballeros')),
         (u'Tarazona', _(u'Tarazona')),
         (u'Utebo', _(u'Utebo')),
         (u'Zaragoza', _(u'Zaragoza')),
         (u'Otro', _(u'Otro'))]

    def getListadoProvincias(self):
        return self.provincias

    def getPosicionProvincias(self, stringProvincia):
        return self.diccionarioProvincias[stringProvincia]

    def getListadoGeneral(self):
        return self.listadoGeneral

    def getHE1correspondiente(self, posicionProvincia, posicionLocalidad):
        return self.listadoGeneral[posicionProvincia][1][posicionLocalidad][1]

    def getHE4correspondiente(self, posicionProvincia, posicionLocalidad):
        return self.listadoGeneral[posicionProvincia][1][posicionLocalidad][3]

    def getNBEcorrespondiente(self, posicionProvincia, posicionLocalidad):
        return self.listadoGeneral[posicionProvincia][1][posicionLocalidad][2]

    def getLocalidadesDeProvincia(self, stringProvincia):
        if stringProvincia == u'':
            return []
        posicionProvincia = self.diccionarioProvincias[stringProvincia]
        listadoLocalidadesDeLaProvincia = [ x[0] for x in self.listadoGeneral[posicionProvincia][1] ]
        aux = []
        for i in self.listadoLocalidades:
            if i[0] in listadoLocalidadesDeLaProvincia:
                aux.append(i)

        if stringProvincia not in ('Ceuta', 'Melilla'):
            aux.append(self.listadoLocalidades[-1])
        return aux

    def getCiudadRepresentativa(self, zonaHE1):
        nombreCiudadRepresentativa, zonaHE1CiudadRepresentativa, zonaNBECiudadRepresentativa, zonaHE4CiudadRepresentativa = self.ciudadRepresentativa[zonaHE1]
        return (nombreCiudadRepresentativa,
         zonaHE1CiudadRepresentativa,
         zonaNBECiudadRepresentativa,
         zonaHE4CiudadRepresentativa)

    def getListadoCCAA(self):
        listadoCCAA = [ x[0] for x in self.listadoCCAA ]
        return listadoCCAA

    def getCCAA(self, stringProvincia):
        for x in self.listadoCCAA:
            if stringProvincia in x[1]:
                ccaa = x[0]

        return ccaa