# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  8 2023, 10:42:25) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: reportlab\__init__.pyc
# Compiled at: 2013-04-04 12:22:40
__version__ = ' $Id$ '
__doc__ = 'The Reportlab PDF generation library.'
Version = '2.7'
import sys
if sys.version_info[0:2] < (2, 5):
    warning = "The trunk of reportlab currently requires Python 2.5 or higher.\n\n    Python 2.3 users may still use ReportLab 2.4 or any other bugfixes\n    derived from it, and Python 2.4 users may use ReportLab 2.5.  \n    Python 2.2 and below need to use released versions beginning with \n    1.x (e.g. 1.21), or snapshots or checkouts from our 'version1' branch.\n    \n    Our current plan is to remove Python 2.5 compatibility on our next release,\n    allowing us to use the 2to3 tool and work on Python 3.0 compatibility.\n    If you have a choice, Python 2.7.x is best long term version to use.\n    "
    raise ImportError('reportlab needs Python 2.5 or higher', warning)

def getStory(context):
    """This is a helper for our old autogenerated documentation system"""
    if context.target == 'UserGuide':
        import os
        myDir = os.path.split(__file__)[0]
        import yaml
        return yaml.parseFile(myDir + os.sep + 'mydocs.yaml')
    else:
        return
        return


def getMonitor():
    import reportlab.monitor
    mon = reportlab.monitor.ReportLabToolkitMonitor()
    return mon